version: '3.8'
services:
  sentiment.ml:
    build:
      context: ./..
      dockerfile: ml/Dockerfile
    environment:
      - DATA_PATH=${DATA_PATH}
      - DATA_FILE=${DATA_FILE}
      - TRAIN_DATA_FILE=${TRAIN_DATA_FILE}
      - TEST_DATA_FILE=${TEST_DATA_FILE}
      - MODEL_PATH=${MODEL_PATH}
      - MODEL_FILE=${MODEL_FILE}
      - METRIC_PATH=${METRIC_PATH}
      - METRIC_FILE=${METRIC_FILE}
    volumes:
      - ./data:/ml/data
      - ./metrics:/ml/metrics
      - ./model:/ml/model
      - ./prepare_data:/ml/prepare_data
      - ./train:/ml/train
      - ./test:/ml/test
      - ./../shared_utils/logger:/ml/utils/logger
