stages:
  pull_data_from_s3:
    cmd: aws s3 cp s3://mlseries/reviews.tsv ./data/reviews.tsv
    outs:
    - ./data/reviews.tsv
  prepare_data:
    cmd: docker-compose run sentiment.ml "python -m prepare_data ."
    deps:
    - data/reviews.tsv
    - prepare_data/__main__.py
    outs:
    - data/test_data.parquet
    - data/train_data.parquet
  train_model:
    cmd: docker-compose run sentiment.ml "python -m train ."
    deps:
    - data/train_data.parquet
    - train/__main__.py
    outs:
    - model/lr.model
  test_model:
    cmd: docker-compose run sentiment.ml "python -m test ."
    deps:
    - data/test_data.parquet
    - model/lr.model
    - test/__main__.py
    metrics:
    - metrics/model_performance.json:
        cache: false
