name: Linting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: psf/black@stable
    - uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - uses: isort/isort-action@v1.0.0
      with:
        requirements-files: "../server/requirements.txt ../ml/requirements.txt"
    
    - name: Install flake8 
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        python -m pip install invoke
    
    - name: Invoke Lint 
      run: |
        # stop the build if there are Python syntax errors or undefined names
        invoke lint