name: Run Unit Tests in ML
env:
    DATA_PATH: "data"
    DATA_FILE: "reviews.tsv"
    TRAIN_DATA_FILE: "train_data.parquet"
    TEST_DATA_FILE: "test_data.parquet"
    MODEL_PATH: "model"
    MODEL_FILE: "lr.model"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev
    paths:
      - 'ml/**'

jobs:
  deploy:
    name: Run Unit Tests for ML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest 
          if [ -f ml/requirements.txt ]; then pip install -r ml/requirements.txt; fi
      - run: |
          cd ml
          pytest