on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev
    paths:
     - 'ml/**'
env:
    DATA_PATH:data
    DATA_FILE:reviews.tsv
    TRAIN_DATA_FILE:train_data.parquet
    TEST_DATA_FILE:test_data.parquet
    MODEL_PATH:model
    MODEL_FILE:lr.model

jobs:
  deploy:
    name: Run Unit Tests for ML
    runs-on: ubuntu-latest
    run: |
      cd ml
      pytest